version: '3.9'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php:
    build:
      context: docker/dev
      args:
        - "USER_ID=${USER_ID-501}"
    volumes:
      - ./:/srv/share/:rw
    environment:
      VIRTUAL_HOST: dev.symfony.com
      VIRTUAL_PORT: 80
      XDEBUG_MODE: develop
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        discover_client_host=true

  db:
    image: mariadb/server:10.5
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'geheim'
      MYSQL_DATABASE: 'app'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:
